ny.times.host=https://api.nytimes.com
ny.times.base.path=/svc/books/v3
ny.times.context.path=/lists/current/
ny.times.api.key=CL3EBjvBSretCXKaGutHGqyjUA0060XK
ny.times.path.list.names=hardcover-fiction.json

goodreads.host=https://www.goodreads.com
goodreads.context.path=/book/title.xml
goodreads.key=JHYKdO4YGeTS4AtJ1WvQ