<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://project1.ericss.com/model/booksInfos"
           xmlns:bk="http://project1.ericss.com/model/booksInfos">
   <xs:element name="getBooksInfosByTitlesRequest" type="bk:titleList"/>
   <xs:complexType name="titleList">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="title" type="xs:string" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="getBooksInfosByTitlesResponse">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="book" type="bk:book" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="book">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="title" type="xs:string"/>
            <xs:element name="author" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="review" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
