//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.09 at 10:23:08 AM EST 
//


package com.ericss.project1.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericss.project1.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetBooksInfosByTitlesRequest_QNAME = new QName("http://project1.ericss.com/ws", "getBooksInfosByTitlesRequest");
    private final static QName _BookAuthor_QNAME = new QName("", "author");
    private final static QName _BookReview_QNAME = new QName("", "review");
    private final static QName _BookDescription_QNAME = new QName("", "description");
    private final static QName _BookTitle_QNAME = new QName("", "title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericss.project1.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBooksInfosByTitlesResponse }
     * 
     */
    public GetBooksInfosByTitlesResponse createGetBooksInfosByTitlesResponse() {
        return new GetBooksInfosByTitlesResponse();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link TitleList }
     * 
     */
    public TitleList createTitleList() {
        return new TitleList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://project1.ericss.com/ws", name = "getBooksInfosByTitlesRequest")
    public JAXBElement<TitleList> createGetBooksInfosByTitlesRequest(TitleList value) {
        return new JAXBElement<TitleList>(_GetBooksInfosByTitlesRequest_QNAME, TitleList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "author", scope = Book.class)
    public JAXBElement<String> createBookAuthor(String value) {
        return new JAXBElement<String>(_BookAuthor_QNAME, String.class, Book.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "review", scope = Book.class)
    public JAXBElement<String> createBookReview(String value) {
        return new JAXBElement<String>(_BookReview_QNAME, String.class, Book.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description", scope = Book.class)
    public JAXBElement<String> createBookDescription(String value) {
        return new JAXBElement<String>(_BookDescription_QNAME, String.class, Book.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = Book.class)
    public JAXBElement<String> createBookTitle(String value) {
        return new JAXBElement<String>(_BookTitle_QNAME, String.class, Book.class, value);
    }

}
