//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.01 at 10:44:01 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://project1.ericss.com/model/booksInfos")
package com.ericss.project1.model.booksinfos;
