//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.12 at 12:38:28 AM EST 
//


package com.ericss.project1.bookinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="titleList" type="{http://project1.ericss.com/bookInfo}titleList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titleList"
})
@XmlRootElement(name = "GetBooksInfosByTitlesRequest")
public class GetBooksInfosByTitlesRequest {

    @XmlElement(required = true)
    protected TitleList titleList;

    /**
     * Gets the value of the titleList property.
     * 
     * @return
     *     possible object is
     *     {@link TitleList }
     *     
     */
    public TitleList getTitleList() {
        return titleList;
    }

    /**
     * Sets the value of the titleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleList }
     *     
     */
    public void setTitleList(TitleList value) {
        this.titleList = value;
    }

}
