//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.16 at 02:42:40 AM EST 
//


package com.ericss.project1.bookinfo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericss.project1.bookinfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericss.project1.bookinfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBooksInfosByTitlesResponse }
     * 
     */
    public GetBooksInfosByTitlesResponse createGetBooksInfosByTitlesResponse() {
        return new GetBooksInfosByTitlesResponse();
    }

    /**
     * Create an instance of {@link BookList }
     * 
     */
    public BookList createBookList() {
        return new BookList();
    }

    /**
     * Create an instance of {@link GetBooksInfosByTitlesRequest }
     * 
     */
    public GetBooksInfosByTitlesRequest createGetBooksInfosByTitlesRequest() {
        return new GetBooksInfosByTitlesRequest();
    }

    /**
     * Create an instance of {@link TitleList }
     * 
     */
    public TitleList createTitleList() {
        return new TitleList();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

}
