//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.16 at 02:42:40 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://project1.ericss.com/bookInfo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ericss.project1.bookinfo;
